// Auth
export const LOGIN_SUCCESS = '@LOGIN_SUCCESS';
export const LOGIN_FAILED = '@LOGIN_FAILED';
export const REGISTER_SUCCESS = '@REGISTER_SUCCESS';
export const REGISTER_FAILED = '@REGISTER_FAILED';

// Buyer
export const GET_BUYER_SUCCESS = '@GET_BUYER_SUCCESS';